<?php

/*
 *  LOGIN.PHP
 *
 *  Allows a user to log in. Just displays a link with the login url 
 *  generated by fb/auth.php
 
 *              Copyright (C) <2013>  <NeaIon>

    This program is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

require_once 'fb/auth.php';

// Redirect to index.php if the user is already logged in
if($user)
  header("Location: index.php");

?>

<!DOCTYPE html>
<html lang="en">
<head>
  <link rel="stylesheet" type="text/css" href="css/style.css" />
</head>
<body>
  <div class='container' style='margin-top: 20px'>
    <div class='page-header'>
      <h1>
        Log in please !
		<small>Nu sunteti logat in aplicatie</small>
      </h1>
    </div>
 
    <? echo "<a class='btn' href=$loginUrl>Sign In</a>"; ?>
  </div>
  <br/><br/>
  <center>
  <a href="http://www.gnu.org/licenses/gpl.html" target="_blank"> 
  <img src="http://www.gnu.org/graphics/gplv3-88x31.png" border="0" />
  </a> 
  <center>
</body>
</html>
